# Generated by Django 4.0.2 on 2022-05-22 08:55

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='background',
            field=models.ImageField(blank=True, default='bg.png', null=True, upload_to='design'),
        ),
        migrations.AddField(
            model_name='design',
            name='borderColor',
            field=colorfield.fields.ColorField(default='#27ff24', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='design',
            name='borderradius',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='design',
            name='header',
            field=models.ImageField(blank=True, default='header.png', null=True, upload_to='header'),
        ),
        migrations.AddField(
            model_name='design',
            name='headingColor',
            field=colorfield.fields.ColorField(default='#ff2124', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='design',
            name='textColor',
            field=colorfield.fields.ColorField(default='#272124', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='design',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
