# Generated by Django 4.0.2 on 2022-05-22 08:59

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_design_background_design_bordercolor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='background',
            new_name='background_image',
        ),
        migrations.AddField(
            model_name='form',
            name='background_image',
            field=models.ImageField(blank=True, default='bg.png', null=True, upload_to='design'),
        ),
        migrations.AddField(
            model_name='form',
            name='borderColor',
            field=colorfield.fields.ColorField(default='#27ff24', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='form',
            name='borderradius',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='form',
            name='header',
            field=models.ImageField(blank=True, default='header.png', null=True, upload_to='header'),
        ),
        migrations.AddField(
            model_name='form',
            name='headingColor',
            field=colorfield.fields.ColorField(default='#ff2124', image_field=None, max_length=18, samples=None),
        ),
    ]
